<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find my_robot_description)/urdf/my_robot_properties.urdf.xacro" />
	<!-- <xacro:include filename="$(find my_robot_description)/urdf/materials.urdf.xacro" /> -->
	<xacro:include filename="$(find my_robot_description)/urdf/my_robot.gazebo.xacro"/>
	<!-- <xacro:include filename="$(find my_robot_description)/urdf/macros.urdf.xacro" /> -->
	

	<!-- Used for fixing robot to Gazebo 'chassis' -->
	<link name="base_footprint"/>

	<joint name="base_joint" type="fixed">
		<parent link="base_footprint"/>
		<child link="chassis"/>
		<origin xyz="0.0 0.0 0.010" rpy="0 0 0"/>
	</joint>


	<link name='chassis'>

		<collision> 
			<origin xyz="0 0 ${wheelRadius}" 
					rpy="0 0 0"/> 
			<geometry> 
				<mesh filename="package://my_robot_description/meshes/chassis.dae"/>
			</geometry> 
		</collision>

		<visual> 
			<origin xyz="0 0 ${wheelRadius}" 
					rpy="0 0 0"/> 
			<geometry>  
				<mesh filename="package://my_robot_description/meshes/chassis.dae"/>
			</geometry> 
			<material name="red"/>
		</visual>

		<inertial> 
			<origin xyz="0 0 ${wheelRadius}" 
					rpy="0 0 0"/> 
			<mass value="${chassisMass}"/> 
			<box_inertia 
				m="${chassisMass}" 
				x="${chassisLength}" 
				y="${chassisWidth}" 
				z="${chassisHeight}"/>
		</inertial>

	</link>


	<joint name="caster_joint" type="fixed">
		<parent link="chassis"/>
		<child link="caster_wheel"/>
	</joint>


	<link name="caster_wheel">

		<collision>
			<origin xyz="${casterOffsetX} 0 ${2*casterRadius}" 
					rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://my_robot_description/meshes/caster_wheel.dae"/>
	  		</geometry>
		</collision>

		<visual> 
			<origin xyz="${casterOffsetX} 0 ${2*casterRadius}" 
					rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://my_robot_description/meshes/caster_wheel.dae"/>
			</geometry>
			<material name="grey"/>
		</visual>

		<inertial>
			<origin xyz="${casterOffsetX} 0 ${2*casterRadius}" 
					rpy="0 0 0"/>
			<mass value="${casterMass}"/>
			<sphere_inertia 
				m="${casterMass}" 
				r="${casterRadius}"/>
		</inertial>

	</link>



	<wheel lr="left" tY="-1"/>
	<wheel lr="right" tY="1"/>


	<!-- Sensor models -->
	<!-- <xacro:include filename="$(find my_robot_description)/urdf/sensors.urdf.xacro"/> -->
</robot>